analyzer:
  exclude:
    - lib/**.config.dart
    - lib/**.graphql.dart
    - lib/routes/**.gr.dart
    - "**.g.dart"
    - build/**
    - lib/l10n/**
    - "**/**.freezed.dart"
    - "**/generated/**"
  errors:
    avoid_unnecessary_containers: warning
    await_only_futures: error
    constant_identifier_names: warning
    empty_constructor_bodies: error
    exhaustive_cases: error
    file_names: error
    library_prefixes: error
    missing_required_param: error
    non_constant_identifier_names: warning
    prefer_if_null_operators: error
    prefer_is_not_empty: error
    prefer_null_aware_operators: error
    unnecessary_const: warning
    unnecessary_new: error
    unnecessary_this: error
    unused_field: warning
    prefer_final_locals: warning
    require_trailing_commas: warning

linter:
  rules:
    avoid_function_literals_in_foreach_calls: true
    avoid_unnecessary_containers: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    constant_identifier_names: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    file_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_if_null_operators: true
    prefer_is_not_empty: true
    prefer_null_aware_operators: true
    unawaited_futures: true
    prefer_single_quotes: true
    sized_box_for_whitespace: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    omit_local_variable_types: false
    sort_constructors_first: false
    prefer_relative_imports: true
    use_super_parameters: true
    require_trailing_commas: true
    avoid_print: true
